---
user: root
key_path: ~/.ssh/id.key
port: 22
hosts: 
 - 1.1.1.1
 - 1.1.1.2
 - 1.1.1.3
 - 1.1.1.4
 - 1.1.1.5
 - 1.1.1.6
 - 1.1.1.7
 - 1.1.1.8
 - 1.1.1.9
 - 1.1.1.10

cmd: |-
  /usr/sbin/ip addr
  touch /tmp/hello.txt
  ls /tmp
